import { describe, it, expect, beforeAll } from "vitest";
import { handleLyricsCallback } from "./webhook";
import { createJob, createLead, updateJobLyricsTaskId } from "./db";
import { nanoid } from "nanoid";

/**
 * Test for webhook lyrics taskId extraction
 * Verifies that both taskId and task_id are correctly handled
 */
describe("Webhook Lyrics TaskId Extraction", () => {
  let testJobId: string;
  let testLyricsTaskId: string;

  beforeAll(async () => {
    // Create test job and lead
    testJobId = nanoid();
    testLyricsTaskId = nanoid();

    await createJob({
      id: testJobId,
      status: "GENERATING_LYRICS",
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    await createLead({
      id: nanoid(),
      jobId: testJobId,
      name: "Test User",
      whatsapp: "+5511999999999",
      story: "Test story for lyrics generation",
      style: "Pop",
      language: "Portuguese",
      createdAt: new Date(),
    });

    // Set lyricsTaskId on the job
    await updateJobLyricsTaskId(testJobId, testLyricsTaskId);

    console.log(`✅ Test setup complete: jobId=${testJobId}, lyricsTaskId=${testLyricsTaskId}`);
  });

  describe("TaskId extraction with camelCase (taskId)", () => {
    it("should extract taskId from camelCase format", async () => {
      const payload = {
        code: 200,
        msg: "All generated successfully.",
        data: {
          callbackType: "complete",
          taskId: testLyricsTaskId, // camelCase
          data: [
            {
              text: "[Verse]\nTest lyrics generated by Suno API\n[Chorus]\nThis is a test",
              title: "Test Song",
              status: "complete",
              errorMessage: ""
            }
          ]
        }
      };

      const req = { body: payload } as any;
      const res = {
        statusCode: 0,
        data: {} as any,
        status: function(code: number) {
          this.statusCode = code;
          return this;
        },
        json: function(data: any) {
          this.data = data;
          return this;
        },
      } as any;

      await handleLyricsCallback(req, res);

      expect(res.statusCode).toBe(200);
      expect(res.data.status).toBe("received");
      expect(res.data.error).toBeUndefined();
      console.log("✅ CamelCase taskId processed successfully");
    });
  });

  describe("TaskId extraction with snake_case (task_id)", () => {
    it("should extract taskId from snake_case format", async () => {
      const payload = {
        code: 200,
        msg: "All generated successfully.",
        data: {
          callback_type: "complete", // snake_case
          task_id: testLyricsTaskId,  // snake_case
          data: [
            {
              text: "[Verse]\nTest lyrics generated by Suno API\n[Chorus]\nThis is a test",
              title: "Test Song",
              status: "complete",
              errorMessage: ""
            }
          ]
        }
      };

      const req = { body: payload } as any;
      const res = {
        statusCode: 0,
        data: {} as any,
        status: function(code: number) {
          this.statusCode = code;
          return this;
        },
        json: function(data: any) {
          this.data = data;
          return this;
        },
      } as any;

      await handleLyricsCallback(req, res);

      expect(res.statusCode).toBe(200);
      expect(res.data.status).toBe("received");
      expect(res.data.error).toBeUndefined();
      console.log("✅ Snake_case task_id processed successfully");
    });
  });

  describe("Missing taskId handling", () => {
    it("should handle missing taskId gracefully", async () => {
      const payload = {
        code: 200,
        msg: "All generated successfully.",
        data: {
          callbackType: "complete",
          // Missing both taskId and task_id
          data: [
            {
              text: "[Verse]\nTest lyrics",
              title: "Test Song",
              status: "complete"
            }
          ]
        }
      };

      const req = { body: payload } as any;
      const res = {
        statusCode: 0,
        data: {} as any,
        status: function(code: number) {
          this.statusCode = code;
          return this;
        },
        json: function(data: any) {
          this.data = data;
          return this;
        },
      } as any;

      await handleLyricsCallback(req, res);

      expect(res.statusCode).toBe(200);
      expect(res.data.status).toBe("received");
      expect(res.data.error).toBe("Missing taskId");
      console.log("✅ Missing taskId handled correctly with error message");
    });
  });

  describe("Invalid payload handling", () => {
    it("should handle invalid payload structure", async () => {
      const payload = {
        code: 200,
        msg: "All generated successfully.",
        // Missing data object
      };

      const req = { body: payload } as any;
      const res = {
        statusCode: 0,
        data: {} as any,
        status: function(code: number) {
          this.statusCode = code;
          return this;
        },
        json: function(data: any) {
          this.data = data;
          return this;
        },
      } as any;

      await handleLyricsCallback(req, res);

      expect(res.statusCode).toBe(200);
      expect(res.data.status).toBe("received");
      expect(res.data.error).toBe("Invalid payload");
      console.log("✅ Invalid payload handled correctly");
    });
  });

  describe("Error callback handling", () => {
    it("should handle error callbacks from Suno API", async () => {
      const payload = {
        code: 500,
        msg: "Lyrics generation failed",
        data: {
          callbackType: "error",
          taskId: testLyricsTaskId,
        }
      };

      const req = { body: payload } as any;
      const res = {
        statusCode: 0,
        data: {} as any,
        status: function(code: number) {
          this.statusCode = code;
          return this;
        },
        json: function(data: any) {
          this.data = data;
          return this;
        },
      } as any;

      await handleLyricsCallback(req, res);

      expect(res.statusCode).toBe(200);
      expect(res.data.status).toBe("received");
      expect(res.data.error).toBeTruthy();
      console.log("✅ Error callback handled with fallback");
    });
  });
});
